### ISSUE TITLE
3D_Repo_GUI_v1_0a_Windows_64bit.zip does not work for me

### ISSUE THREAD

**Issue by wsdflink** [3drepo/3drepogui#115]
Do i need to config anything? The following shows the Error info:
Application Error
The application was unable to start correctly (0xc000007b). Click OK to close the application.

**Comment by wsdflink** [comment]
I figure it out by installing OpenSSL.

**Comment by jozefdobos** [comment]
This info might be useful re versions: https://github.com/3drepo/3drepobouncer/wiki/Compiling-MongoDB-CXX-Driver

**Comment by jozefdobos** [comment]
@carmenfan can you pls check this is bundled correctly?

**Comment by carmenfan** [comment]
it should be, it was sufficient when I tested it on the vanilla win 1. @wsdflink what version of Windows are you using? also, do you have a copy of visual studio installed?

The error is quite different when it was missing the open SSL dlls (it complained about not being able to find something within mongoclient.dll instead of this error message. A quick google seems to point to some misconfiguration on visual studio library.

**Comment by wsdflink** [comment]
I am using win7 64bit and visual studio 2013. After i installed OpenSSL in system library path, it can work.

**Comment by carmenfan** [comment]
I've just tried it on my home laptop (win7). Whilst it seems to work happily with win10 , win 7 seems to need a few extras:

- the libeay32.dll attached seems to be of the wrong version (even though it should be correct...), fixed by installing openSSL on my machine
- it's missing visual studio redistribution packages, which can be found in MS website.

Need to fix this for next release.

**Comment by carmenfan** [comment]
This is fixed in #110 . The installer should now bundle in all the dependencies needed
