### ISSUE TITLE
Add dialog for map tiles

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#38]
Add a simple dialog similar to Transformation dialog that lets you set and attach map tiles.

**Comment by carmenfan** [comment]
It's working and been working for a while i guess. Also been moved to the new GUI #40. changed the interface so it scales when you stretch the window and also uses the Spin boxes instead of plain text. I personally think the interface still look ugly as hell so at some point Jozef/someone with a better design brain might want to look into it.

But I consider this closed!
