### ISSUE TITLE
Multipart integration

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepogui#39]
Integrate changes to core for multipart with the GUI.

**Comment by carmenfan** [comment]
Closing this issue, new multipart related issues will now be on #45

This is due to the branch for this issue is targeted at 3drepocore/gui combo, and core has since been deprecated. The changes from this issue has been ported to bouncer, any new changes regarding the gui that utilise the new bouncer would make more sense to be in a new issue (and less crazy merges with everything getting deleted!)
