### ISSUE TITLE
Refactor all filenames

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#53]
Refactor all filenames to match the reverse naming scheme of 3D Repo Bouncer library

**Comment by carmenfan** [comment]
Would also be nice to have folders loosely related to the namespaces.

for e.g. all the gui classes should reside in repo/gui instead of being at the root directory of the src folder. (so whoever developing and hit an error can follow the namespace convention to find the file)

any new classes I created already conform (repo/workers, repo/logger) to this, just haven't got around to moving everything else around yet.

**Comment by jozefdobos** [comment]
Agreed, I kinda tried to comply already (but sort of failed yet).

**Comment by carmenfan** [comment]
Refactoring mapping will be stored here:

https://docs.google.com/a/3drepo.org/spreadsheets/d/1jgGOxHKrR1bj9WKtpOeH9pg1nmtxzU02kLy9pBtNlIM/edit?usp=sharing

**Comment by carmenfan** [comment]
done
