### ISSUE TITLE
Graph consumes a lot of memory and does not clean up

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepogui#97]

**Comment by carmenfan** [comment]
The memory leak has been plugged.

Regarding to the large memory usage, it is using using over 4GB on my machine rendering the bridge, even the fully loaded unoptimised + stash of 3D Repo Worlld + GLC_World is using less memory than that

My suspicion is that this is due to the crazy amount of QGraphicsItems that is generated (every node is generating a new ellipse, and every relationship is generating a line). How to go about fixing it i'm not entirely sure. But random googling on QGraphicsItems it seems like you could render the same item in different places which will reduce the amount of items enormously. However, we will lose the ability to use the tooltip to display the RepoNode info, unless we hijack it it one way or the other.

Moving this onto Beta as the urgent part has been done.
